title: Spark-fi
description: No spark is too small to fire a dream
author: Oberron
github: https://github.com/oberron
about: No spark is too small to fire a dream
disqus_shortname: disqus_e5sxXi13p5
google_analytics: UA-XXXXXXXX-Y
#avatar_url: /spark2-fi/static/img/avatar.jpg
avatar_url: /spark-fi/static/img/spark.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/oberron"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/oberron"
    - icon: fa-stack-exchange
      link: "https://stackexchange.com/users/1195495/oberron"
    - icon: fa-github
      link: "https://github.com/oberron/spark-fi"
    - icon: fa-whatsapp
      link: "https://wa.me/?text=https%3A%2F%2Foberron.github.io%2Fspark-fi"

share:
  twitter_username: oberron
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://oberron.github.io"
baseurl: "/spark-fi"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
#  - jekyll-sitemap
  - jekyll-feed
defaults:
  -
    values:
      layout: "post"
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
