theme: jekyll-theme-architect
name: spark-fi
description: No spark is too small to fire a dream
disqus: oberron
paginate: 5 # amount of posts to show
paginate_path: /page:num/
---
layout: default
comments: true
# other options
---
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
